defaults:
  - baseline.yaml

exp:
  name: feat_normcurv

features:
  use_normals: true
  use_curvature: true
  use_radius: true

precompute:
  enabled: true
  cache_dir: processed/raw_cls/v13_main4_feat_normcurv_cache
  k_neighbors: 30
