defaults:
  - teeth3ds_fdi_pretrain_supcon_norot_tta0_posfeat_ls0_dropout0p1.yaml
  - ../data_v21_main4_seg_small1_cloudid_eq.yaml

exp:
  name: teeth3ds_fdi_pretrain_supcon_norot_tta0_posfeat_ls0_dropout0p1_seg_small1_cloudid_eq

features:
  point_features: [xyz, cloud_id]

