defaults:
  - teeth3ds_fdi_pretrain_supcon_norot_tta0_posfeat_ls0_dropout0p1_seg_all_cloudid_eq.yaml

exp:
  name: teeth3ds_fdi_pretrain_ce_norot_tta0_posfeat_ls0_dropout0p1_seg_all_cloudid_eq

loss:
  supcon_weight: 0.0

